#!/usr/bin/env bash

# To work, I have to be called pre-commit,
# have execute permission +x,
# and live in <git repo>/.git/hooks

FORBIDDEN='.DS_Store'

git diff --cached --name-only --diff-filter=ACMRT | \
while read file; do
	if [[ $(basename $file) = $FORBIDDEN ]]; then
		git rm --cached "$file" &> /dev/null && \
			echo "Hook removed $file (git rm --cached)"
	fi
done
